class Config:
    API_V1_PREFIX = "/api/v1"
    
    DEFAULT_PAGE_SIZE = 20
    MAX_PAGE_SIZE = 100
    
    RATE_LIMIT_REQUESTS = 100
    RATE_LIMIT_WINDOW = 60
    
    STREAM_CHUNK_SIZE = 1024
    STREAM_TIMEOUT = 30
